# Generated by Django 4.2.11 on 2025-10-31 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "Authentification",
            "0008_remove_agent_service_remove_directeur_service_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificatAMC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("etat", models.CharField(blank=True, max_length=25, null=True)),
                ("dateDemande", models.DateField(blank=True, null=True)),
                ("dateEtatVersement", models.DateField(blank=True, null=True)),
                ("dateQuittance", models.DateField(blank=True, null=True)),
                ("dateCertificat", models.DateField(blank=True, null=True)),
                (
                    "nomMarchandise",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("paysOrigine", models.CharField(blank=True, max_length=25, null=True)),
                ("quantite", models.FloatField(blank=True, null=True)),
                ("unite", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Authentification.agent",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "directeur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Authentification.directeur",
                    ),
                ),
                (
                    "ordsec",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Authentification.ordsec",
                    ),
                ),
                (
                    "tresorier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Authentification.tresorier",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
