# Generated by Django 4.2.11 on 2025-10-31 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Certificats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificatamc",
            name="numero",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
