# Generated by Django 4.2.11 on 2025-10-31 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "Authentification",
            "0008_remove_agent_service_remove_directeur_service_and_more",
        ),
        ("Certificats", "0002_certificatamc_numero"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificatamc",
            name="operateur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Authentification.operateur",
            ),
        ),
        migrations.AddField(
            model_name="certificatamc",
            name="reference",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
