# Generated by Django 4.2.11 on 2025-11-12 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("Certificats", "0003_certificatamc_operateur_certificatamc_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificatamc",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="certificatamc",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
