# Generated by Django 4.2.11 on 2025-11-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Certificats", "0004_alter_certificatamc_content_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sigle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sigleCertificatamc",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
            ],
        ),
    ]
