# Generated by Django 4.2.11 on 2025-11-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Certificats", "0005_sigle"),
    ]

    operations = [
        migrations.AddField(
            model_name="sigle",
            name="sigleAgrementppn",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
