# Generated by Django 4.2.11 on 2025-11-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Certificats", "0006_sigle_sigleagrementppn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sigle",
            name="sigleAgrementppn",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="sigle",
            name="sigleCertificatamc",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
