# Generated by Django 4.2.11 on 2025-12-03 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentification', '0005_alter_agent_service_content_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificatAMC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=15, null=True)),
                ('reference', models.CharField(blank=True, max_length=20, null=True)),
                ('date_demande', models.DateField(auto_now_add=True)),
                ('date_etat_versement', models.DateField(blank=True, null=True)),
                ('date_quittance', models.DateField(blank=True, null=True)),
                ('date_certificat', models.DateField(blank=True, null=True)),
                ('nom_marchandise', models.CharField(max_length=100)),
                ('pays_origine', models.CharField(max_length=100)),
                ('quantite', models.IntegerField()),
                ('unite', models.CharField(max_length=10)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authentification.agent')),
                ('directeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authentification.directeur')),
                ('operateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authentification.operateur')),
                ('ordsec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authentification.ordsec')),
                ('tresorier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authentification.tresorier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
