# Generated by Django 4.2.11 on 2025-12-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sigle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigle_amc', models.CharField(blank=True, max_length=10, null=True)),
                ('sigle_agrement', models.CharField(blank=True, max_length=10, null=True)),
                ('sigle_cipens', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
