# Generated by Django 4.2.11 on 2025-12-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificat', '0002_sigle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sigle',
            name='sigle_agrement',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='sigle',
            name='sigle_amc',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='sigle',
            name='sigle_cipens',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
