# Generated by Django 4.2.11 on 2025-12-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificat', '0003_alter_sigle_sigle_agrement_alter_sigle_sigle_amc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatamc',
            name='etat',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='certificatamc',
            name='numero',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='certificatamc',
            name='reference',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
