# Generated by Django 4.2.11 on 2025-12-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificat', '0004_certificatamc_etat_alter_certificatamc_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatamc',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='certificatamc',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
