# Generated by Django 5.2.8 on 2025-11-26 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nif', models.CharField(max_length=20)),
                ('stat', models.CharField(max_length=20)),
                ('raison_sociale', models.CharField(max_length=100)),
                ('adresse_pro', models.CharField(max_length=100)),
                ('phone_pro', models.CharField(max_length=100)),
                ('phone_perso', models.CharField(max_length=100)),
                ('adresse_perso', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
