# Generated by Django 4.2.11 on 2025-11-27 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentification', '0002_fonctionnaire'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fonctionnaire',
            new_name='Agent',
        ),
        migrations.CreateModel(
            name='Tresorier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20)),
                ('adresse_pro', models.CharField(max_length=100)),
                ('adresse_perso', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('fonction', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20)),
                ('adresse_pro', models.CharField(max_length=100)),
                ('adresse_perso', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('fonction', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ordsec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20)),
                ('adresse_pro', models.CharField(max_length=100)),
                ('adresse_perso', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('fonction', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Directeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20)),
                ('adresse_pro', models.CharField(max_length=100)),
                ('adresse_perso', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('fonction', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
