# Generated by Django 4.2.11 on 2025-10-19 01:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Authentification', '0002_tresorier_sg_ordsecret_directeur_agent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ordsecret',
            new_name='Ordsec',
        ),
    ]
