# Generated by Django 4.2.11 on 2025-10-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0003_rename_ordsecret_ordsec'),
    ]

    operations = [
        migrations.AddField(
            model_name='operateur',
            name='adresse',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='operateur',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='operateur',
            name='raisonSociale',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
