# Generated by Django 4.2.11 on 2025-11-28 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('authentification', '0003_rename_fonctionnaire_agent_tresorier_sg_ordsec_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='service',
        ),
        migrations.RemoveField(
            model_name='directeur',
            name='service',
        ),
        migrations.RemoveField(
            model_name='ordsec',
            name='service',
        ),
        migrations.RemoveField(
            model_name='sg',
            name='service',
        ),
        migrations.RemoveField(
            model_name='tresorier',
            name='service',
        ),
        migrations.AddField(
            model_name='agent',
            name='service_content_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='service_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='directeur',
            name='service_content_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='directeur',
            name='service_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='ordsec',
            name='service_content_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ordsec',
            name='service_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='sg',
            name='service_content_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sg',
            name='service_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='tresorier',
            name='service_content_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tresorier',
            name='service_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype'),
        ),
    ]
