# Generated by Django 4.2.11 on 2025-10-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentification", "0004_operateur_adresse_operateur_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operateur",
            name="nif",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="operateur",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
