# Generated by Django 4.2.11 on 2025-10-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentification", "0005_alter_operateur_nif_alter_operateur_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operateur",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
