# Generated by Django 4.2.11 on 2025-10-24 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "Authentification",
            "0007_agent_adres_pro_agent_phone_agent_role_agent_service_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="service",
        ),
        migrations.RemoveField(
            model_name="directeur",
            name="service",
        ),
        migrations.RemoveField(
            model_name="ordsec",
            name="service",
        ),
        migrations.RemoveField(
            model_name="sg",
            name="service",
        ),
        migrations.RemoveField(
            model_name="tresorier",
            name="service",
        ),
        migrations.AddField(
            model_name="agent",
            name="service_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="service_object_id",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="directeur",
            name="service_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="directeur",
            name="service_object_id",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ordsec",
            name="service_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="ordsec",
            name="service_object_id",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sg",
            name="service_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="sg",
            name="service_object_id",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tresorier",
            name="service_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="tresorier",
            name="service_object_id",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
