# Generated by Django 4.2.11 on 2025-12-03 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionRegionale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_direction', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='servicecommerce',
            name='direction_regionale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.directionregionale'),
        ),
        migrations.AddField(
            model_name='serviceconditionnement',
            name='direction_regionale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.directionregionale'),
        ),
        migrations.AddField(
            model_name='servicemetrologie',
            name='direction_regionale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.directionregionale'),
        ),
    ]
