# Generated by Django 4.2.11 on 2025-12-03 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_directionregionale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directionregionale',
            name='region',
        ),
    ]
